#!/usr/bin/env python3
"""Turn the Aseprite artwork in assets/art/mitsos into src/mitsosart.asm.

Mitsos is a mode 1 game: four pens, four pixels to a byte, square pixels. The
pictures come out of assets/aseprite/mitsos.aseprite, one PNG per frame, and
every pixel has to be one of the four pens exactly - anything else is a
mistake in the art and is refused rather than guessed at.

The format written here is the one src/sprite.asm already draws: width in
bytes, height, then a mask/data pair per byte,

    screen = (screen AND mask) OR data

with the two interleaved so one pointer feeds both. Each sprite is also
written out mirrored, as spr_<name>_l, so Mitsos can face the way he is
walking: reversing a mode 1 row means swapping the pixels inside every byte
as well as the bytes themselves, which is not something to do three times a
frame.

    tools/mkmitsos.py                write src/mitsosart.asm
    tools/mkmitsos.py --show STAND   print one picture as the monitor shapes it
"""

import os
import sys

from cpcpng import read_png     # tools/ is on the path: this is run from there

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "assets", "art", "mitsos")
OUT = os.path.join(ROOT, "src", "mitsosart.asm")

PIXELS_PER_BYTE = 4

#: Where a pixel's two pen bits live, leftmost pixel first, least significant
#: bit first: pixel 0 is bits 7 and 3, pixel 1 bits 6 and 2, and so on. So a
#: byte of solid pen 1 is #F0 and of pen 2 is #0F - see config.asm.
PEN_BITS = tuple((7 - i, 3 - i) for i in range(PIXELS_PER_BYTE))

#: pal_shop, as RGB. The comment is the hardware colour number.
PENS = [
    (0, 0, 128),        # 0   4 navy      - the night, and what shows through
    (0, 255, 255),      # 1  19 cyan      - tiles, sea, ice, his eyes
    (255, 128, 0),      # 2  14 orange    - Mitsos, the fish, the cheese
    (255, 255, 255),    # 3  11 white     - highlights, foam, text
]
BY_RGB = {rgb: i for i, rgb in enumerate(PENS)}


def read_art(path):
    """One PNG -> rows of pen numbers, with None for transparent."""
    w, h, colour, plte, trns, rows = read_png(path)
    name = os.path.basename(path)
    pixels = []
    for y, line in enumerate(rows):
        row = []
        for x in range(w):
            if colour == 6:
                r, g, b, a = line[4 * x:4 * x + 4]
            elif colour == 2:
                r, g, b = line[3 * x:3 * x + 3]
                a = 255
            else:
                i = line[x]
                r, g, b = plte[3 * i:3 * i + 3]
                a = trns[i] if trns and i < len(trns) else 255
            if a < 128:
                row.append(None)
                continue
            pen = BY_RGB.get((r, g, b))
            if pen is None:
                sys.exit("%s: pixel %d,%d is #%02X%02X%02X, which is not one "
                         "of the four pens" % (name, x, y, r, g, b))
            row.append(pen)
        pixels.append(row)
    if w % PIXELS_PER_BYTE:
        sys.exit("%s: %d pixels wide; mode 1 packs four to a byte" % (name, w))
    return w, h, pixels


def encode_masked(row):
    """A sprite row -> (mask, data) pairs. Transparent keeps the background."""
    out = []
    for i in range(0, len(row), PIXELS_PER_BYTE):
        mask = data = 0
        for j, pen in enumerate(row[i:i + PIXELS_PER_BYTE]):
            bits = PEN_BITS[j]
            if pen is None:
                for b in bits:
                    mask |= 1 << b
            else:
                for k, b in enumerate(bits):
                    if pen & (1 << k):
                        data |= 1 << b
        out.append((mask, data))
    return out


def picture(row):
    return "".join("." if p is None else "%X" % p for p in row)


def mirrored(rows):
    return [list(reversed(r)) for r in rows]


def load():
    if not os.path.isdir(ART):
        sys.exit("mkmitsos: no %s" % ART)
    names = sorted(n for n in os.listdir(ART) if n.endswith(".png"))
    return [(n[:-4].upper(),) + read_art(os.path.join(ART, n)) for n in names]


def show(want):
    for name, w, h, rows in load():
        if want and not name.endswith(want.upper()):
            continue
        print("%s  %d x %d pixels, %d bytes across"
              % (name, w, h, w // PIXELS_PER_BYTE))
        for row in rows:
            print("  " + picture(row).replace("0", "."))
        print()


def main():
    if "--show" in sys.argv:
        i = sys.argv.index("--show")
        show(sys.argv[i + 1] if len(sys.argv) > i + 1 else None)
        return

    sprites = load()
    total = 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(";; Generated by tools/mkmitsos.py from assets/art/mitsos - "
                 "do not edit.\n;;\n")
        fh.write(";; Drawn in Aseprite: assets/aseprite/mitsos.aseprite holds "
                 "every frame,\n;; four pens, and is the copy to change.\n\n")
        fh.write(";; Width in bytes, height, then mask/data pairs:\n")
        fh.write(";;   screen = (screen AND mask) OR data\n\n")
        for name, w, h, _rows in sprites:
            fh.write("SPR_%-14s EQU %d\n" % (name + "_W", w // PIXELS_PER_BYTE))
            fh.write("SPR_%-14s EQU %d\n" % (name + "_H", h))
        fh.write(";; The widest of them, for the length of the unrolled blit.\n")
        fh.write("ART_MAX_W          EQU %d\n"
                 % max(w // PIXELS_PER_BYTE for _n, w, _h, _r in sprites))
        for name, w, h, rows in sprites:
            for suffix, art in (("", rows), ("_l", mirrored(rows))):
                if suffix and art == rows:
                    fh.write("\nspr_%s_l EQU spr_%s      ; the same either way\n"
                             % (name.lower(), name.lower()))
                    continue
                fh.write("\n;; %s - %d x %d pixels%s\nspr_%s%s\n"
                         % (name, w, h,
                            ", facing the other way" if suffix else "",
                            name.lower(), suffix))
                fh.write("    defb %d,%d\n" % (w // PIXELS_PER_BYTE, h))
                total += 2 + 2 * h * (w // PIXELS_PER_BYTE)
                for row in art:
                    pairs = encode_masked(row)
                    fh.write("    defb %-40s ; %s\n"
                             % (",".join("#%02X,#%02X" % p for p in pairs),
                                picture(row).replace("0", ".")))
    print("mkmitsos: %d sprites (%d bytes) -> %s"
          % (len(sprites), total, os.path.relpath(OUT, ROOT)))


if __name__ == "__main__":
    main()
