#!/usr/bin/env python3
"""Turn assets/sprites.txt into src/sprites.asm.

Sprites are stored mask-then-data, byte by byte, so the blit is

    screen = (screen AND mask) OR data

with both operands read straight off an advancing pointer. Mode 0 spreads one
pixel's four pen bits across bits 7,3,5,1 of a byte for the left pixel and
6,2,4,0 for the right, so a transparent pixel means setting all four of its
bits in the mask and none in the data.

Sprites are byte aligned: they move 2 pixels at a time horizontally, which on
a mode 0 screen is the same 4/384ths of the width a mode 1 sprite moved. Moving
a pixel at a time needs two pre-shifted copies of every frame, which is worth
doing when something actually looks wrong, not before.

A ":name" line ending in "flip" also gets a mirrored copy, as spr_<name>_l, so
whatever it is can face the way it is going. Only the two enemies in this file
ask for one: the cat is drawn front on and never turns round, and mirroring its
five frames would cost a kilobyte and a half to no purpose.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "assets", "sprites.txt")
PIXELS_PER_BYTE = 2
OUT = os.path.join(ROOT, "src", "sprites.asm")


def read_art():
    sprites = []
    name = None
    flip = False
    rows = []
    with open(ART, encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.rstrip("\n")
            if line.startswith(":"):
                if name is not None:
                    sprites.append((name, rows, lineno, flip))
                word = line[1:].split()
                name = word[0]
                flip = "flip" in word[1:]
                rows = []
                continue
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if name is None:
                sys.exit("%s:%d: pixel row before any \":name\"" % (ART, lineno))
            bad = set(line) - set(".0123456789ABCDEF")
            if bad:
                sys.exit("%s:%d: %s may only contain . and a pen 0-9 A-F, "
                         "found %s" % (ART, lineno, name, "".join(sorted(bad))))
            rows.append(line)
    if name is not None:
        sprites.append((name, rows, lineno, flip))

    for name, rows, lineno, _flip in sprites:
        if not rows:
            sys.exit("%s: sprite %s has no rows" % (ART, name))
        width = len(rows[0])
        if width % PIXELS_PER_BYTE:
            sys.exit("%s: sprite %s is %d pixels wide; mode 0 sprites must be "
                     "a multiple of %d" % (ART, name, width, PIXELS_PER_BYTE))
        for r in rows:
            if len(r) != width:
                sys.exit("%s: sprite %s has rows of %d and %d pixels"
                         % (ART, name, width, len(r)))
    return [(n, r, f) for n, r, _l, f in sprites]


#: Where each of a pixel's four pen bits lives, left pixel then right.
PEN_BITS = ((7, 3, 5, 1), (6, 2, 4, 0))


def encode_row(row):
    """One pixel row -> a list of (mask, data) byte pairs."""
    out = []
    for i in range(0, len(row), PIXELS_PER_BYTE):
        mask = data = 0
        for j, ch in enumerate(row[i:i + PIXELS_PER_BYTE]):
            bits = PEN_BITS[j]
            if ch == ".":
                for b in bits:
                    mask |= 1 << b            # keep every bit of the background
            else:
                pen = int(ch, 16)
                for k, b in enumerate(bits):
                    if pen & (1 << k):
                        data |= 1 << b
        out.append((mask, data))
    return out


def main():
    sprites = read_art()
    biggest = 0
    widest = 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(";; Generated by tools/mksprite.py from assets/sprites.txt "
                 "- do not edit.\n;;\n")
        fh.write(";; Each sprite is width-in-bytes, height, then mask/data pairs.\n")
        fh.write(";; Blit is  screen = (screen AND mask) OR data.\n\n")
        body = []
        for name, rows, flip in sprites:
            wbytes = len(rows[0]) // PIXELS_PER_BYTE
            height = len(rows)
            biggest = max(biggest, wbytes * height)
            widest = max(widest, wbytes)
            label = "spr_" + name.lower()
            fh.write("SPR_%-12s EQU %s\n" % (name + "_W", wbytes))
            fh.write("SPR_%-12s EQU %s\n" % (name + "_H", height))
            body.append((name, label, wbytes, height, rows, flip))
        fh.write("\n;; Largest sprite, for sizing the background save buffers,\n")
        fh.write(";; and the widest, for the length of the unrolled blit.\n")
        fh.write("SPR_MAX_BYTES EQU %d\n" % biggest)
        fh.write("SPR_MAX_W     EQU %d\n" % widest)
        for name, label, wbytes, height, rows, flip in body:
            mirror = [r[::-1] for r in rows]
            for suffix, art in (("", rows),) + ((("_l", mirror),) if flip else ()):
                if suffix and art == rows:
                    fh.write("\n%s_l EQU %s          ; the same either way\n"
                             % (label, label))
                    continue
                fh.write("\n;; %s - %d x %d pixels%s\n%s%s\n"
                         % (name, wbytes * PIXELS_PER_BYTE, height,
                            ", facing the other way" if suffix else "",
                            label, suffix))
                fh.write("    defb %d,%d\n" % (wbytes, height))
                for row in art:
                    pairs = encode_row(row)
                    fh.write("    defb %-40s ; %s\n"
                             % (",".join("#%02X,#%02X" % p for p in pairs), row))
    print("mksprite: %d sprites, largest %d bytes of background to save"
          % (len(sprites), biggest))


if __name__ == "__main__":
    main()
