#!/usr/bin/env python3
"""Turn assets/sprites.txt into src/sprites.asm.

Sprites are stored mask-then-data, byte by byte, so the blit is

    screen = (screen AND mask) OR data

with both operands read straight off an advancing pointer. Mode 1 spreads one
pixel's two pen bits across bits 7-i and 3-i of a byte, so a transparent pixel
means setting both of those in the mask and neither in the data.

Sprites are byte aligned: they move 4 pixels at a time horizontally. Moving a
pixel at a time needs four pre-shifted copies of every frame, which is worth
doing when something actually looks wrong, not before.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "assets", "sprites.txt")
OUT = os.path.join(ROOT, "src", "sprites.asm")


def read_art():
    sprites = []
    name = None
    rows = []
    with open(ART, encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.rstrip("\n")
            if line.startswith(":"):
                if name is not None:
                    sprites.append((name, rows, lineno))
                name = line[1:].strip()
                rows = []
                continue
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if name is None:
                sys.exit("%s:%d: pixel row before any \":name\"" % (ART, lineno))
            bad = set(line) - set(".0123")
            if bad:
                sys.exit("%s:%d: %s may only contain . 0 1 2 3, found %s"
                         % (ART, lineno, name, "".join(sorted(bad))))
            rows.append(line)
    if name is not None:
        sprites.append((name, rows, lineno))

    for name, rows, lineno in sprites:
        if not rows:
            sys.exit("%s: sprite %s has no rows" % (ART, name))
        width = len(rows[0])
        if width % 4:
            sys.exit("%s: sprite %s is %d pixels wide; mode 1 sprites must be "
                     "a multiple of 4" % (ART, name, width))
        for r in rows:
            if len(r) != width:
                sys.exit("%s: sprite %s has rows of %d and %d pixels"
                         % (ART, name, width, len(r)))
    return [(n, r) for n, r, _ in sprites]


def encode_row(row):
    """One pixel row -> a list of (mask, data) byte pairs."""
    out = []
    for i in range(0, len(row), 4):
        mask = data = 0
        for j, ch in enumerate(row[i:i + 4]):
            if ch == ".":
                mask |= (1 << (7 - j)) | (1 << (3 - j))
            else:
                pen = int(ch)
                if pen & 1:
                    data |= 1 << (7 - j)
                if pen & 2:
                    data |= 1 << (3 - j)
        out.append((mask, data))
    return out


def main():
    sprites = read_art()
    biggest = 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(";; Generated by tools/mksprite.py from assets/sprites.txt "
                 "- do not edit.\n;;\n")
        fh.write(";; Each sprite is width-in-bytes, height, then mask/data pairs.\n")
        fh.write(";; Blit is  screen = (screen AND mask) OR data.\n\n")
        body = []
        for name, rows in sprites:
            wbytes = len(rows[0]) // 4
            height = len(rows)
            biggest = max(biggest, wbytes * height)
            label = "spr_" + name.lower()
            fh.write("SPR_%-12s EQU %s\n" % (name + "_W", wbytes))
            fh.write("SPR_%-12s EQU %s\n" % (name + "_H", height))
            body.append((name, label, wbytes, height, rows))
        fh.write("\n;; Largest sprite, for sizing the background save buffers.\n")
        fh.write("SPR_MAX_BYTES EQU %d\n" % biggest)
        for name, label, wbytes, height, rows in body:
            fh.write("\n;; %s - %d x %d pixels\n%s\n" % (name, wbytes * 4, height, label))
            fh.write("    defb %d,%d\n" % (wbytes, height))
            for row in rows:
                pairs = encode_row(row)
                fh.write("    defb %-40s ; %s\n"
                         % (",".join("#%02X,#%02X" % p for p in pairs), row))
    print("mksprite: %d sprites, largest %d bytes of background to save"
          % (len(sprites), biggest))


if __name__ == "__main__":
    main()
