;; Generated by tools/mktext.py from assets/font8.txt - do not edit.
;;
;; 8x8 cells, drawn 6 wide and 7 tall so the spare column and row are the
;; letter spacing. Greek capitals that share a Latin shape are not repeated;
;; the text tool folds them onto the Latin glyph.

GL_SPACE  EQU 0
GL_A      EQU 1
GL_B      EQU 2
GL_C      EQU 3
GL_D      EQU 4
GL_E      EQU 5
GL_F      EQU 6
GL_G      EQU 7
GL_H      EQU 8
GL_I      EQU 9
GL_J      EQU 10
GL_K      EQU 11
GL_L      EQU 12
GL_M      EQU 13
GL_N      EQU 14
GL_O      EQU 15
GL_P      EQU 16
GL_Q      EQU 17
GL_R      EQU 18
GL_S      EQU 19
GL_T      EQU 20
GL_U      EQU 21
GL_V      EQU 22
GL_W      EQU 23
GL_X      EQU 24
GL_Y      EQU 25
GL_Z      EQU 26
GL_GAMMA  EQU 27
GL_DELTA  EQU 28
GL_THETA  EQU 29
GL_LAMBDA EQU 30
GL_XI     EQU 31
GL_PI     EQU 32
GL_SIGMA  EQU 33
GL_PHI    EQU 34
GL_PSI    EQU 35
GL_OMEGA  EQU 36
GL_0      EQU 37
GL_1      EQU 38
GL_2      EQU 39
GL_3      EQU 40
GL_4      EQU 41
GL_5      EQU 42
GL_6      EQU 43
GL_7      EQU 44
GL_8      EQU 45
GL_9      EQU 46
GL_DOT    EQU 47
GL_COMMA  EQU 48
GL_BANG   EQU 49
GL_QUERY  EQU 50
GL_COLON  EQU 51
GL_DASH   EQU 52
GL_QUOTE  EQU 53

;; Greek-only glyphs are named in full because rasm labels are ASCII:
;; Γ = GL_GAMMA, Δ = GL_DELTA, Θ = GL_THETA, Λ = GL_LAMBDA, Ξ = GL_XI, Π = GL_PI, Σ = GL_SIGMA, Φ = GL_PHI, Ψ = GL_PSI, Ω = GL_OMEGA

GLYPH_COUNT EQU 54

font
    ;; SPACE
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
    ;; A
    defb %01111000
    defb %10000100
    defb %10000100
    defb %11111100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %00000000
    ;; B
    defb %11111000
    defb %10000100
    defb %10000100
    defb %11111000
    defb %10000100
    defb %10000100
    defb %11111000
    defb %00000000
    ;; C
    defb %01111000
    defb %10000100
    defb %10000000
    defb %10000000
    defb %10000000
    defb %10000100
    defb %01111000
    defb %00000000
    ;; D
    defb %11111000
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %11111000
    defb %00000000
    ;; E
    defb %11111100
    defb %10000000
    defb %10000000
    defb %11110000
    defb %10000000
    defb %10000000
    defb %11111100
    defb %00000000
    ;; F
    defb %11111100
    defb %10000000
    defb %10000000
    defb %11110000
    defb %10000000
    defb %10000000
    defb %10000000
    defb %00000000
    ;; G
    defb %01111000
    defb %10000100
    defb %10000000
    defb %10011100
    defb %10000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; H
    defb %10000100
    defb %10000100
    defb %10000100
    defb %11111100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %00000000
    ;; I
    defb %01111000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %01111000
    defb %00000000
    ;; J
    defb %00111100
    defb %00011000
    defb %00011000
    defb %00011000
    defb %00011000
    defb %10011000
    defb %01110000
    defb %00000000
    ;; K
    defb %10000100
    defb %10001000
    defb %10010000
    defb %11100000
    defb %10010000
    defb %10001000
    defb %10000100
    defb %00000000
    ;; L
    defb %10000000
    defb %10000000
    defb %10000000
    defb %10000000
    defb %10000000
    defb %10000000
    defb %11111100
    defb %00000000
    ;; M
    defb %10000100
    defb %11001100
    defb %11111100
    defb %10110100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %00000000
    ;; N
    defb %10000100
    defb %11000100
    defb %11100100
    defb %10110100
    defb %10011100
    defb %10001100
    defb %10000100
    defb %00000000
    ;; O
    defb %01111000
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; P
    defb %11111000
    defb %10000100
    defb %10000100
    defb %11111000
    defb %10000000
    defb %10000000
    defb %10000000
    defb %00000000
    ;; Q
    defb %01111000
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10110100
    defb %10001000
    defb %01110100
    defb %00000000
    ;; R
    defb %11111000
    defb %10000100
    defb %10000100
    defb %11111000
    defb %10010000
    defb %10001000
    defb %10000100
    defb %00000000
    ;; S
    defb %01111000
    defb %10000100
    defb %10000000
    defb %01111000
    defb %00000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; T
    defb %11111100
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00000000
    ;; U
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; V
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %01001000
    defb %00110000
    defb %00000000
    ;; W
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10110100
    defb %11111100
    defb %11001100
    defb %10000100
    defb %00000000
    ;; X
    defb %10000100
    defb %10000100
    defb %01001000
    defb %00110000
    defb %01001000
    defb %10000100
    defb %10000100
    defb %00000000
    ;; Y
    defb %10000100
    defb %10000100
    defb %01001000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00000000
    ;; Z
    defb %11111100
    defb %00001000
    defb %00010000
    defb %00100000
    defb %01000000
    defb %10000000
    defb %11111100
    defb %00000000
    ;; GAMMA
    defb %11111100
    defb %10000000
    defb %10000000
    defb %10000000
    defb %10000000
    defb %10000000
    defb %10000000
    defb %00000000
    ;; DELTA
    defb %00110000
    defb %00110000
    defb %01001000
    defb %01001000
    defb %10000100
    defb %10000100
    defb %11111100
    defb %00000000
    ;; THETA
    defb %01111000
    defb %10000100
    defb %10000100
    defb %11111100
    defb %10000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; LAMBDA
    defb %00110000
    defb %00110000
    defb %01001000
    defb %01001000
    defb %10000100
    defb %10000100
    defb %10000100
    defb %00000000
    ;; XI
    defb %11111100
    defb %00000000
    defb %00000000
    defb %01111000
    defb %00000000
    defb %00000000
    defb %11111100
    defb %00000000
    ;; PI
    defb %11111100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %00000000
    ;; SIGMA
    defb %11111100
    defb %10000000
    defb %01000000
    defb %00100000
    defb %01000000
    defb %10000000
    defb %11111100
    defb %00000000
    ;; PHI
    defb %00100000
    defb %01110000
    defb %10101000
    defb %10101000
    defb %10101000
    defb %01110000
    defb %00100000
    defb %00000000
    ;; PSI
    defb %10101000
    defb %10101000
    defb %10101000
    defb %01110000
    defb %00100000
    defb %00100000
    defb %01110000
    defb %00000000
    ;; OMEGA
    defb %01111000
    defb %10000100
    defb %10000100
    defb %10000100
    defb %10000100
    defb %01001000
    defb %11001100
    defb %00000000
    ;; 0
    defb %01111000
    defb %10001100
    defb %10010100
    defb %10100100
    defb %11000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; 1
    defb %00110000
    defb %01110000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %01111000
    defb %00000000
    ;; 2
    defb %01111000
    defb %10000100
    defb %00000100
    defb %00111000
    defb %01000000
    defb %10000000
    defb %11111100
    defb %00000000
    ;; 3
    defb %01111000
    defb %10000100
    defb %00000100
    defb %00111000
    defb %00000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; 4
    defb %00011000
    defb %00111000
    defb %01011000
    defb %10011000
    defb %11111100
    defb %00011000
    defb %00011000
    defb %00000000
    ;; 5
    defb %11111100
    defb %10000000
    defb %10000000
    defb %11111000
    defb %00000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; 6
    defb %01111000
    defb %10000100
    defb %10000000
    defb %11111000
    defb %10000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; 7
    defb %11111100
    defb %00000100
    defb %00001000
    defb %00010000
    defb %00100000
    defb %00100000
    defb %00100000
    defb %00000000
    ;; 8
    defb %01111000
    defb %10000100
    defb %10000100
    defb %01111000
    defb %10000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; 9
    defb %01111000
    defb %10000100
    defb %10000100
    defb %01111100
    defb %00000100
    defb %10000100
    defb %01111000
    defb %00000000
    ;; DOT
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00110000
    defb %00110000
    defb %00000000
    ;; COMMA
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00110000
    defb %00110000
    defb %01100000
    defb %00000000
    ;; BANG
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00110000
    defb %00000000
    defb %00110000
    defb %00000000
    ;; QUERY
    defb %01111000
    defb %10000100
    defb %00000100
    defb %00011000
    defb %00110000
    defb %00000000
    defb %00110000
    defb %00000000
    ;; COLON
    defb %00000000
    defb %00110000
    defb %00110000
    defb %00000000
    defb %00110000
    defb %00110000
    defb %00000000
    defb %00000000
    ;; DASH
    defb %00000000
    defb %00000000
    defb %00000000
    defb %11111100
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
    ;; QUOTE
    defb %00110000
    defb %00110000
    defb %00100000
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
    defb %00000000
font_end

    ASSERT (font_end-font)/8 == GLYPH_COUNT
