; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 3.

Start
StartDisarkGenerateExternalLabel

DisarkByteRegionStart0
    db "AT30"
DisarkPointerRegionStart1
    dw ArpeggioTable    ; The address of the Arpeggio table.
    dw PitchTable    ; The address of the Pitch table.
    dw InstrumentTable    ; The address of the Instrument table.
    dw EffectBlockTable    ; The address of the Effect Block table.
DisarkPointerRegionEnd1


; The addresses of each Subsong.
DisarkPointerRegionStart2
    dw Subsong0_Start
DisarkPointerRegionEnd2

; Declares all the Arpeggios.
ArpeggioTable
DisarkPointerRegionStart3
DisarkPointerRegionEnd3

; Declares all the Pitches.
PitchTable
DisarkPointerRegionStart4
DisarkPointerRegionEnd4

; Declares all the Instruments.
InstrumentTable
DisarkPointerRegionStart5
    dw EmptyInstrument
    dw Instrument1
DisarkPointerRegionEnd5

EmptyInstrument
    db 0    ; The speed (>0, 0 for 256).

    db 0    ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

Instrument1
    db 1    ; The speed (>0, 0 for 256).

    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 177    ; Soft only. Volume: 6. Volume only.

    db 169    ; Soft only. Volume: 5. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 145    ; Soft only. Volume: 2. Volume only.

    db 137    ; Soft only. Volume: 1. Volume only.

    db 6    ; Loop to silence.


; The indexes of the effect blocks used by this song.
EffectBlockTable
DisarkPointerRegionStart6
    dw EffectBlock_P4P1    ; Index 0
DisarkPointerRegionEnd6
EffectBlock_P4P1
    db 4
    db 1


DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Subsong0_DisarkByteRegionStart0
Subsong0_Start
    db 2    ; ReplayFrequency (0=12.5hz, 1=25hz, 2=50hz, 3=100hz, 4=150hz, 5=300hz).
    db 1    ; Digichannel (>=0).
    db 1    ; PSG count (>0).
    db 0    ; Loop start index (>=0).
    db 1    ; End index (>=0).
    db 5    ; Initial speed (>=0).
    db 16    ; Base note index (>=0).

Subsong0_Linker
Subsong0_DisarkPointerRegionStart1
; Position 0
Subsong0_Linker_Loop
    dw Subsong0_Track0
    dw Subsong0_Track1
    dw Subsong0_Track1
    dw Subsong0_LinkerBlock0
; Position 1
    dw Subsong0_Track2
    dw Subsong0_Track1
    dw Subsong0_Track1
    dw Subsong0_LinkerBlock0
Subsong0_DisarkPointerRegionEnd1
    dw 0    ; Loop.
Subsong0_DisarkWordForceReference2
    dw Subsong0_Linker_Loop

Subsong0_LinkerBlock0
    db 64    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
Subsong0_DisarkWordForceReference3
    dw Subsong0_SpeedTrack0    ; SpeedTrack address.
Subsong0_DisarkWordForceReference4
    dw Subsong0_EventTrack0    ; EventTrack address.


Subsong0_Track0
    db 220
    db 1    ; New Instrument (1).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 55
    db 60    ; Waits for 1 line.

    db 48
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 47
    db 60    ; Waits for 1 line.

    db 52
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 48
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 24
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 17
    db 60    ; Waits for 1 line.

    db 35
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 40
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 47
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 43
    db 60    ; Waits for 1 line.

    db 28
    db 60    ; Waits for 1 line.

    db 47
    db 60    ; Waits for 1 line.

    db 43
    db 60    ; Waits for 1 line.

    db 48
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 19
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 52
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track1
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track2
    db 164
    db 1    ; New Instrument (1).
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 55
    db 60    ; Waits for 1 line.

    db 48
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 21
    db 60    ; Waits for 1 line.

    db 52
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 43
    db 60    ; Waits for 1 line.

    db 40
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 40
    db 60    ; Waits for 1 line.

    db 55
    db 60    ; Waits for 1 line.

    db 48
    db 60    ; Waits for 1 line.

    db 17
    db 60    ; Waits for 1 line.

    db 47
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 40
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 17
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 43
    db 60    ; Waits for 1 line.

    db 19
    db 60    ; Waits for 1 line.

    db 31
    db 60    ; Waits for 1 line.

    db 36
    db 60    ; Waits for 1 line.

    db 35
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 47
    db 60    ; Waits for 1 line.

    db 28
    db 60    ; Waits for 1 line.

    db 52
    db 61
    db 127    ; Waits for 128 lines.


; The speed tracks
Subsong0_SpeedTrack0
    db 255    ; Wait for 128 lines.

; The event tracks
Subsong0_EventTrack0
    db 255    ; Wait for 128 lines.

Subsong0_DisarkByteRegionEnd0
