;; Generated by tools/mktext.py from text/mitsos.*.txt - do not edit.
;;
;; Strings are length-prefixed runs of glyph indices, so the drawing code
;; can centre a line without scanning it first.

LANG_EN  EQU 0    ; ENGLISH
LANG_EL  EQU 1    ; GREEK
LANG_COUNT EQU 2

MSG_LIVES      EQU 0
MSG_GAMEOVER   EQU 1
MSG_AGAIN      EQU 2
MSG_COUNT EQU 3

;; language -> table of message pointers
lang_tables
    defw msgtab_en
    defw msgtab_el

msgtab_en
    defw str_en_LIVES
    defw str_en_GAMEOVER
    defw str_en_AGAIN

msgtab_el
    defw str_el_LIVES
    defw str_el_GAMEOVER
    defw str_el_AGAIN

str_en_LIVES
    defb 5
    defb 12,9,22,5,19
str_en_GAMEOVER
    defb 9
    defb 7,1,13,5,0,15,22,5,18
str_en_AGAIN
    defb 23
    defb 16,18,5,19,19,0,6,9,18,5,0,20,15,0,20,18
    defb 25,0,1,7,1,9,14

str_el_LIVES
    defb 4
    defb 26,36,5,33
str_el_GAMEOVER
    defb 5
    defb 20,5,30,15,33
str_el_AGAIN
    defb 18
    defb 32,1,20,1,0,6,9,18,5,0,27,9,1,0,31,1
    defb 14,1
