;; Generated by tools/mktext.py from text/mitsos.*.txt - do not edit.
;;
;; Strings are length-prefixed runs of glyph indices, so the drawing code
;; can centre a line without scanning it first.

LANG_EN  EQU 0    ; ENGLISH
LANG_EL  EQU 1    ; GREEK
LANG_COUNT EQU 2

MSG_SCORE      EQU 0
MSG_LIVES      EQU 1
MSG_GAMEOVER   EQU 2
MSG_DONE       EQU 3
MSG_AGAIN      EQU 4
MSG_TITLE1     EQU 5
MSG_TITLE2     EQU 6
MSG_PRESS      EQU 7
MSG_LANGHINT   EQU 8
MSG_COUNT EQU 9

;; language -> table of message pointers
lang_tables
    defw msgtab_en
    defw msgtab_el

msgtab_en
    defw str_en_SCORE
    defw str_en_LIVES
    defw str_en_GAMEOVER
    defw str_en_DONE
    defw str_en_AGAIN
    defw str_en_TITLE1
    defw str_en_TITLE2
    defw str_en_PRESS
    defw str_en_LANGHINT

msgtab_el
    defw str_el_SCORE
    defw str_el_LIVES
    defw str_el_GAMEOVER
    defw str_el_DONE
    defw str_el_AGAIN
    defw str_el_TITLE1
    defw str_el_TITLE2
    defw str_el_PRESS
    defw str_el_LANGHINT

str_en_SCORE
    defb 5
    defb 19,3,15,18,5
str_en_LIVES
    defb 5
    defb 12,9,22,5,19
str_en_GAMEOVER
    defb 9
    defb 7,1,13,5,0,15,22,5,18
str_en_DONE
    defb 9
    defb 23,5,12,12,0,4,15,14,5
str_en_AGAIN
    defb 23
    defb 16,18,5,19,19,0,6,9,18,5,0,20,15,0,20,18
    defb 25,0,1,7,1,9,14
str_en_TITLE1
    defb 6
    defb 13,9,20,19,15,19
str_en_TITLE2
    defb 17
    defb 20,8,5,0,7,18,15,3,5,18,25,0,8,5,9,19
    defb 20
str_en_PRESS
    defb 19
    defb 16,18,5,19,19,0,6,9,18,5,0,20,15,0,19,20
    defb 1,18,20
str_en_LANGHINT
    defb 17
    defb 16,18,5,19,19,0,12,0,6,15,18,0,7,18,5,5
    defb 11

str_el_SCORE
    defb 4
    defb 33,11,15,16
str_el_LIVES
    defb 4
    defb 26,36,5,33
str_el_GAMEOVER
    defb 5
    defb 20,5,30,15,33
str_el_DONE
    defb 6
    defb 13,32,16,1,2,15
str_el_AGAIN
    defb 18
    defb 32,1,20,1,0,6,9,18,5,0,27,9,1,0,31,1
    defb 14,1
str_el_TITLE1
    defb 7
    defb 32,1,14,9,11,15,33
str_el_TITLE2
    defb 15
    defb 33,20,15,0,32,1,14,20,15,32,36,30,5,9,15
str_el_PRESS
    defb 18
    defb 32,1,20,1,0,6,9,18,5,0,27,9,1,0,1,16
    defb 24,8
str_el_LANGHINT
    defb 18
    defb 32,1,20,1,0,12,0,27,9,1,0,1,27,27,30,9
    defb 11,1
