;; Generated by tools/mkrooms.py from assets/mitsos/rooms.txt
;; - do not edit. The format, and why there is a generator at
;; all, are at the top of the tool.
;;
;; These are assembled at ROOM_BANK for bank 4 and never run in
;; place: src/mitsosbank.asm saves the image, the file carries
;; it, and rooms_to_bank puts it where it belongs at boot.

ROOM_COUNT      EQU 4

;; --- 1: the shop --------------------------------------------------
    ORG ROOM_BANK+0*ROOM_BLOCK
    defb 8                          ; where he comes in
    defb 26, SHELF_4-20         ; the way out
    defb 30, 50                 ; her beat
    defb PEN1_BYTE, PEN15_BYTE, PEN10_BYTE, PEN5_BYTE, PEN3_BYTE
    defb #40+7
    ORG ROOM_BANK+0*ROOM_BLOCK+R_PLAT
    defb 0, 95, FLOOR_TOP
    defb 4, 33, SHELF_1
    defb 4, 33, SHELF_2
    defb 4, 33, SHELF_3
    defb 4, 33, SHELF_4
    defb 38, 51, SHELF_1-8
    defb 56, 87, SHELF_1-24
    defb #FF
    ASSERT $ <= ROOM_BANK+0*ROOM_BLOCK+R_PROPS
    ORG ROOM_BANK+0*ROOM_BLOCK+R_PROPS
    defb 58, 24
    defw box_window
    defb 4, 76
    defw box_shelving
    defb 56, SHELF_1-24
    defw box_counter
    defb 38, SHELF_1-8
    defw box_crates
    defb 88, 212
    defw box_sacks
    defb #FF
    ASSERT $ <= ROOM_BANK+0*ROOM_BLOCK+R_SOAP
    ORG ROOM_BANK+0*ROOM_BLOCK+R_SOAP
    defb 34, 50, FLOOR_TOP
    defb 58, 74, FLOOR_TOP
    defb #FF
    ASSERT $ <= ROOM_BANK+0*ROOM_BLOCK+R_PICKS
    ORG ROOM_BANK+0*ROOM_BLOCK+R_PICKS
    defw spr_fish
    defb 8, SHELF_4-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_cheese
    defb 22, SHELF_3-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_sausage
    defb 62, SHELF_1-24-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_meatball
    defb 42, SHELF_1-8-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_catnip
    defb 10, SHELF_2-SPR_FISH_H, 0, 1, #FF, 0
    ASSERT $ == ROOM_BANK+0*ROOM_BLOCK+R_FOES
    ORG ROOM_BANK+0*ROOM_BLOCK+R_FOES
    defb K_MOUSE, 80, FLOOR_TOP-SPR_MOUSE_A_H, 0, 56, 92, -1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, 0, 0, 0
    defb K_MOUSE, 58, SHELF_1-24-SPR_MOUSE_A_H, 0, 58, 84, 1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, STEAL_START, 0, 0
    defb K_GULL, 64, 72, 72, 58, 84, 1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, 0, 0, 0
    ASSERT $ == ROOM_BANK+0*ROOM_BLOCK+ROOM_USED

;; --- 2: the store room --------------------------------------------
    ORG ROOM_BANK+1*ROOM_BLOCK
    defb 8                          ; where he comes in
    defb 66, SHELF_4-20         ; the way out
    defb 24, 56                 ; her beat
    defb PEN10_BYTE, PEN10_BYTE, PEN10_BYTE, PEN6_BYTE, PEN15_BYTE
    defb #40+6
    ORG ROOM_BANK+1*ROOM_BLOCK+R_PLAT
    defb 0, 95, FLOOR_TOP
    defb 66, 95, SHELF_1
    defb 66, 95, SHELF_2
    defb 66, 95, SHELF_3
    defb 66, 95, SHELF_4
    defb 8, 21, SHELF_1-8
    defb 24, 37, SHELF_2-8
    defb 40, 53, SHELF_1-8
    defb #FF
    ASSERT $ <= ROOM_BANK+1*ROOM_BLOCK+R_PROPS
    ORG ROOM_BANK+1*ROOM_BLOCK+R_PROPS
    defb 66, 76
    defw box_shelving
    defb 8, SHELF_1-8
    defw box_crates
    defb 24, SHELF_2-8
    defw box_crates
    defb 40, SHELF_1-8
    defw box_crates
    defb 56, 212
    defw box_sacks
    defb #FF
    ASSERT $ <= ROOM_BANK+1*ROOM_BLOCK+R_SOAP
    ORG ROOM_BANK+1*ROOM_BLOCK+R_SOAP
    defb 54, 66, FLOOR_TOP
    defb #FF
    ASSERT $ <= ROOM_BANK+1*ROOM_BLOCK+R_PICKS
    ORG ROOM_BANK+1*ROOM_BLOCK+R_PICKS
    defw spr_sausage
    defb 10, SHELF_1-8-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_meatball
    defb 26, SHELF_2-8-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_fish
    defb 70, SHELF_2-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_cheese
    defb 86, SHELF_4-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_catnip
    defb 78, SHELF_3-SPR_FISH_H, 0, 1, #FF, 0
    ASSERT $ == ROOM_BANK+1*ROOM_BLOCK+R_FOES
    ORG ROOM_BANK+1*ROOM_BLOCK+R_FOES
    defb K_MOUSE, 30, FLOOR_TOP-SPR_MOUSE_A_H, 0, 24, 62, 1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, STEAL_START, 0, 0
    defb K_MOUSE, 70, SHELF_1-SPR_MOUSE_A_H, 0, 66, 90, 1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, 0, 0, 0
    defb K_MOUSE, 84, SHELF_3-SPR_MOUSE_A_H, 0, 66, 90, -1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, STEAL_REST, 0, 0
    ASSERT $ == ROOM_BANK+1*ROOM_BLOCK+ROOM_USED

;; --- 3: the cold room ---------------------------------------------
    ORG ROOM_BANK+2*ROOM_BLOCK
    defb 88                         ; where he comes in
    defb 4, SHELF_4-20         ; the way out
    defb 36, 66                 ; her beat
    defb PEN3_BYTE, PEN5_BYTE, PEN10_BYTE, PEN5_BYTE, PEN11_BYTE
    defb #40+19
    ORG ROOM_BANK+2*ROOM_BLOCK+R_PLAT
    defb 0, 95, FLOOR_TOP
    defb 4, 33, SHELF_1
    defb 4, 33, SHELF_2
    defb 4, 33, SHELF_3
    defb 4, 33, SHELF_4
    defb 42, 65, SHELF_1-8
    defb 66, 89, SHELF_1-8
    defb #FF
    ASSERT $ <= ROOM_BANK+2*ROOM_BLOCK+R_PROPS
    ORG ROOM_BANK+2*ROOM_BLOCK+R_PROPS
    defb 4, 76
    defw box_rack
    defb 42, SHELF_1-8
    defw box_icebox
    defb 66, SHELF_1-8
    defw box_icebox
    defb #FF
    ASSERT $ <= ROOM_BANK+2*ROOM_BLOCK+R_SOAP
    ORG ROOM_BANK+2*ROOM_BLOCK+R_SOAP
    defb #FF
    ASSERT $ <= ROOM_BANK+2*ROOM_BLOCK+R_PICKS
    ORG ROOM_BANK+2*ROOM_BLOCK+R_PICKS
    defw spr_fish
    defb 6, SHELF_3-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_meatball
    defb 22, SHELF_2-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_cheese
    defb 8, SHELF_4-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_sausage
    defb 78, SHELF_1-8-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_catnip
    defb 46, SHELF_1-8-SPR_FISH_H, 0, 1, #FF, 0
    ASSERT $ == ROOM_BANK+2*ROOM_BLOCK+R_FOES
    ORG ROOM_BANK+2*ROOM_BLOCK+R_FOES
    defb K_MOUSE, 52, FLOOR_TOP-SPR_MOUSE_A_H, 0, 36, 70, -1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, STEAL_START, 0, 0
    defb K_MOUSE, 10, SHELF_2-SPR_MOUSE_A_H, 0, 4, 30, 1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, 0, 0, 0
    defb K_GULL, 56, 64, 64, 40, 76, 1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, 0, 0, 0
    ASSERT $ == ROOM_BANK+2*ROOM_BLOCK+ROOM_USED

;; --- 4: the yard --------------------------------------------------
    ORG ROOM_BANK+3*ROOM_BLOCK
    defb 4                          ; where he comes in
    defb 76, SHELF_3-20         ; the way out
    defb 28, 64                 ; her beat
    defb PEN11_BYTE, PEN11_BYTE, PEN6_BYTE, PEN5_BYTE, PEN5_BYTE
    defb #40+19
    ORG ROOM_BANK+3*ROOM_BLOCK+R_PLAT
    defb 0, 95, FLOOR_TOP
    defb 6, 19, SHELF_3
    defb 6, 19, SHELF_2
    defb 6, 19, SHELF_1
    defb 76, 89, SHELF_3
    defb 76, 89, SHELF_2
    defb 76, 89, SHELF_1
    defb 38, 51, SHELF_1-8
    defb #FF
    ASSERT $ <= ROOM_BANK+3*ROOM_BLOCK+R_PROPS
    ORG ROOM_BANK+3*ROOM_BLOCK+R_PROPS
    defb 20, DADO_TOP
    defw box_gate
    defb 6, SHELF_3
    defw box_stack
    defb 76, SHELF_3
    defw box_stack
    defb 38, SHELF_1-8
    defw box_crates
    defb 60, 212
    defw box_sacks
    defb #FF
    ASSERT $ <= ROOM_BANK+3*ROOM_BLOCK+R_SOAP
    ORG ROOM_BANK+3*ROOM_BLOCK+R_SOAP
    defb 22, 36, FLOOR_TOP
    defb 62, 74, FLOOR_TOP
    defb #FF
    ASSERT $ <= ROOM_BANK+3*ROOM_BLOCK+R_PICKS
    ORG ROOM_BANK+3*ROOM_BLOCK+R_PICKS
    defw spr_fish
    defb 8, SHELF_2-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_sausage
    defb 40, SHELF_1-8-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_cheese
    defb 78, SHELF_2-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_meatball
    defb 78, SHELF_1-SPR_FISH_H, 1, 1, #FF, 0
    defw spr_catnip
    defb 8, SHELF_1-SPR_FISH_H, 0, 1, #FF, 0
    ASSERT $ == ROOM_BANK+3*ROOM_BLOCK+R_FOES
    ORG ROOM_BANK+3*ROOM_BLOCK+R_FOES
    defb K_MOUSE, 46, FLOOR_TOP-SPR_MOUSE_A_H, 0, 22, 70, 1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, STEAL_START, 0, 0
    defb K_GULL, 34, 60, 60, 24, 66, 1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, 0, 0, 0
    defb K_GULL, 70, 92, 92, 52, 88, -1
    defb FOE_TICK, 0, FOE_ANIM, 0, 0, 0, 0, 0, D_NONE, 100, 0, 0
    ASSERT $ == ROOM_BANK+3*ROOM_BLOCK+ROOM_USED

    ORG ROOM_BANK+ROOM_COUNT*ROOM_BLOCK
rooms_end
