;; Generated by tools/mktext.py from text/loukoumas.*.txt - do not edit.
;;
;; Strings are length-prefixed runs of glyph indices, so the drawing code
;; can centre a line without scanning it first.

LANG_EN  EQU 0    ; ENGLISH
LANG_EL  EQU 1    ; GREEK
LANG_COUNT EQU 2

MSG_TITLE1     EQU 0
MSG_TITLE2     EQU 1
MSG_PRESS      EQU 2
MSG_LANGNAME   EQU 3
MSG_LANGHINT   EQU 4
MSG_SCORE      EQU 5
MSG_LIVES      EQU 6
MSG_SAUSAGES   EQU 7
MSG_LEVEL      EQU 8
MSG_PAUSED     EQU 9
MSG_GAMEOVER   EQU 10
MSG_WELLDONE   EQU 11
MSG_ROOM1      EQU 12
MSG_ROOM2      EQU 13
MSG_ROOM3      EQU 14
MSG_ROOM4      EQU 15
MSG_ROOM5      EQU 16
MSG_ROOM6      EQU 17
MSG_ROOM7      EQU 18
MSG_ROOM8      EQU 19
MSG_ROOM9      EQU 20
MSG_ROOM10     EQU 21
MSG_COUNT EQU 22

;; language -> table of message pointers
lang_tables
    defw msgtab_en
    defw msgtab_el

msgtab_en
    defw str_en_TITLE1
    defw str_en_TITLE2
    defw str_en_PRESS
    defw str_en_LANGNAME
    defw str_en_LANGHINT
    defw str_en_SCORE
    defw str_en_LIVES
    defw str_en_SAUSAGES
    defw str_en_LEVEL
    defw str_en_PAUSED
    defw str_en_GAMEOVER
    defw str_en_WELLDONE
    defw str_en_ROOM1
    defw str_en_ROOM2
    defw str_en_ROOM3
    defw str_en_ROOM4
    defw str_en_ROOM5
    defw str_en_ROOM6
    defw str_en_ROOM7
    defw str_en_ROOM8
    defw str_en_ROOM9
    defw str_en_ROOM10

msgtab_el
    defw str_el_TITLE1
    defw str_el_TITLE2
    defw str_el_PRESS
    defw str_el_LANGNAME
    defw str_el_LANGHINT
    defw str_el_SCORE
    defw str_el_LIVES
    defw str_el_SAUSAGES
    defw str_el_LEVEL
    defw str_el_PAUSED
    defw str_el_GAMEOVER
    defw str_el_WELLDONE
    defw str_el_ROOM1
    defw str_el_ROOM2
    defw str_el_ROOM3
    defw str_el_ROOM4
    defw str_el_ROOM5
    defw str_el_ROOM6
    defw str_el_ROOM7
    defw str_el_ROOM8
    defw str_el_ROOM9
    defw str_el_ROOM10

str_en_TITLE1
    defb 9
    defb 12,15,21,11,15,21,13,1,19
str_en_TITLE2
    defb 21
    defb 20,8,5,0,7,18,5,1,20,0,6,18,9,4,7,5
    defb 0,18,1,9,4
str_en_PRESS
    defb 19
    defb 16,18,5,19,19,0,6,9,18,5,0,20,15,0,19,20
    defb 1,18,20
str_en_LANGNAME
    defb 7
    defb 5,14,7,12,9,19,8
str_en_LANGHINT
    defb 17
    defb 16,18,5,19,19,0,12,0,6,15,18,0,7,18,5,5
    defb 11
str_en_SCORE
    defb 5
    defb 19,3,15,18,5
str_en_LIVES
    defb 5
    defb 12,9,22,5,19
str_en_SAUSAGES
    defb 8
    defb 19,1,21,19,1,7,5,19
str_en_LEVEL
    defb 5
    defb 12,5,22,5,12
str_en_PAUSED
    defb 6
    defb 16,1,21,19,5,4
str_en_GAMEOVER
    defb 9
    defb 7,1,13,5,0,15,22,5,18
str_en_WELLDONE
    defb 10
    defb 23,5,12,12,0,4,15,14,5,49
str_en_ROOM1
    defb 8
    defb 2,1,19,5,13,5,14,20
str_en_ROOM2
    defb 6
    defb 7,1,18,1,7,5
str_en_ROOM3
    defb 6
    defb 7,1,18,4,5,14
str_en_ROOM4
    defb 7
    defb 8,1,12,12,23,1,25
str_en_ROOM5
    defb 7
    defb 2,5,4,18,15,15,13
str_en_ROOM6
    defb 8
    defb 23,1,18,4,18,15,2,5
str_en_ROOM7
    defb 8
    defb 2,1,20,8,18,15,15,13
str_en_ROOM8
    defb 5
    defb 19,20,21,4,25
str_en_ROOM9
    defb 6
    defb 12,15,21,14,7,5
str_en_ROOM10
    defb 7
    defb 11,9,20,3,8,5,14

str_el_TITLE1
    defb 9
    defb 30,15,25,11,15,25,13,1,33
str_el_TITLE2
    defb 28
    defb 8,0,13,5,27,1,30,8,0,5,32,9,28,16,15,13
    defb 8,0,33,20,15,0,35,25,27,5,9,15
str_el_PRESS
    defb 22
    defb 32,1,20,1,0,6,9,18,5,0,27,9,1,0,5,11
    defb 11,9,14,8,33,8
str_el_LANGNAME
    defb 8
    defb 5,30,30,8,14,9,11,1
str_el_LANGHINT
    defb 18
    defb 32,1,20,1,0,12,0,27,9,1,0,1,27,27,30,9
    defb 11,1
str_el_SCORE
    defb 4
    defb 33,11,15,16
str_el_LIVES
    defb 4
    defb 26,36,5,33
str_el_SAUSAGES
    defb 9
    defb 30,15,25,11,1,14,9,11,1
str_el_LEVEL
    defb 5
    defb 32,9,33,20,1
str_el_PAUSED
    defb 5
    defb 32,1,25,33,8
str_el_GAMEOVER
    defb 5
    defb 20,5,30,15,33
str_el_WELLDONE
    defb 7
    defb 13,32,16,1,2,15,49
str_el_ROOM1
    defb 7
    defb 25,32,15,27,5,9,15
str_el_ROOM2
    defb 6
    defb 27,11,1,16,1,26
str_el_ROOM3
    defb 5
    defb 11,8,32,15,33
str_el_ROOM4
    defb 7
    defb 5,9,33,15,28,15,33
str_el_ROOM5
    defb 11
    defb 25,32,14,15,28,36,13,1,20,9,15
str_el_ROOM6
    defb 8
    defb 14,20,15,25,30,1,32,1
str_el_ROOM7
    defb 6
    defb 13,32,1,14,9,15
str_el_ROOM8
    defb 7
    defb 27,16,1,34,5,9,15
str_el_ROOM9
    defb 6
    defb 33,1,30,15,14,9
str_el_ROOM10
    defb 7
    defb 11,15,25,26,9,14,1
