;; Generated by tools/mktext.py from text/loukoumas.*.txt - do not edit.
;;
;; Strings are length-prefixed runs of glyph indices, so the drawing code
;; can centre a line without scanning it first.

LANG_EN  EQU 0    ; ENGLISH
LANG_EL  EQU 1    ; GREEK
LANG_COUNT EQU 2

MSG_TITLE1     EQU 0
MSG_TITLE2     EQU 1
MSG_PRESS      EQU 2
MSG_LANGNAME   EQU 3
MSG_LANGHINT   EQU 4
MSG_SCORE      EQU 5
MSG_LIVES      EQU 6
MSG_SAUSAGES   EQU 7
MSG_LEVEL      EQU 8
MSG_PAUSED     EQU 9
MSG_GAMEOVER   EQU 10
MSG_WELLDONE   EQU 11
MSG_ROOM1      EQU 12
MSG_ROOM2      EQU 13
MSG_COUNT EQU 14

;; language -> table of message pointers
lang_tables
    defw msgtab_en
    defw msgtab_el

msgtab_en
    defw str_en_TITLE1
    defw str_en_TITLE2
    defw str_en_PRESS
    defw str_en_LANGNAME
    defw str_en_LANGHINT
    defw str_en_SCORE
    defw str_en_LIVES
    defw str_en_SAUSAGES
    defw str_en_LEVEL
    defw str_en_PAUSED
    defw str_en_GAMEOVER
    defw str_en_WELLDONE
    defw str_en_ROOM1
    defw str_en_ROOM2

msgtab_el
    defw str_el_TITLE1
    defw str_el_TITLE2
    defw str_el_PRESS
    defw str_el_LANGNAME
    defw str_el_LANGHINT
    defw str_el_SCORE
    defw str_el_LIVES
    defw str_el_SAUSAGES
    defw str_el_LEVEL
    defw str_el_PAUSED
    defw str_el_GAMEOVER
    defw str_el_WELLDONE
    defw str_el_ROOM1
    defw str_el_ROOM2

str_en_TITLE1
    defb 9
    defb 12,15,21,11,15,21,13,1,19
str_en_TITLE2
    defb 21
    defb 20,8,5,0,7,18,5,1,20,0,6,18,9,4,7,5
    defb 0,18,1,9,4
str_en_PRESS
    defb 19
    defb 16,18,5,19,19,0,6,9,18,5,0,20,15,0,19,20
    defb 1,18,20
str_en_LANGNAME
    defb 7
    defb 5,14,7,12,9,19,8
str_en_LANGHINT
    defb 17
    defb 16,18,5,19,19,0,12,0,6,15,18,0,7,18,5,5
    defb 11
str_en_SCORE
    defb 5
    defb 19,3,15,18,5
str_en_LIVES
    defb 5
    defb 12,9,22,5,19
str_en_SAUSAGES
    defb 8
    defb 19,1,21,19,1,7,5,19
str_en_LEVEL
    defb 5
    defb 12,5,22,5,12
str_en_PAUSED
    defb 6
    defb 16,1,21,19,5,4
str_en_GAMEOVER
    defb 9
    defb 7,1,13,5,0,15,22,5,18
str_en_WELLDONE
    defb 10
    defb 23,5,12,12,0,4,15,14,5,49
str_en_ROOM1
    defb 6
    defb 12,15,21,14,7,5
str_en_ROOM2
    defb 7
    defb 11,9,20,3,8,5,14

str_el_TITLE1
    defb 9
    defb 30,15,25,11,15,25,13,1,33
str_el_TITLE2
    defb 28
    defb 8,0,13,5,27,1,30,8,0,5,32,9,28,16,15,13
    defb 8,0,33,20,15,0,35,25,27,5,9,15
str_el_PRESS
    defb 22
    defb 32,1,20,1,0,6,9,18,5,0,27,9,1,0,5,11
    defb 11,9,14,8,33,8
str_el_LANGNAME
    defb 8
    defb 5,30,30,8,14,9,11,1
str_el_LANGHINT
    defb 18
    defb 32,1,20,1,0,12,0,27,9,1,0,1,27,27,30,9
    defb 11,1
str_el_SCORE
    defb 4
    defb 33,11,15,16
str_el_LIVES
    defb 4
    defb 26,36,5,33
str_el_SAUSAGES
    defb 9
    defb 30,15,25,11,1,14,9,11,1
str_el_LEVEL
    defb 5
    defb 32,9,33,20,1
str_el_PAUSED
    defb 5
    defb 32,1,25,33,8
str_el_GAMEOVER
    defb 5
    defb 20,5,30,15,33
str_el_WELLDONE
    defb 7
    defb 13,32,16,1,2,15,49
str_el_ROOM1
    defb 6
    defb 33,1,30,15,14,9
str_el_ROOM2
    defb 7
    defb 11,15,25,26,9,14,1
